---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
  namespace: training-lab
spec:
  rules:
    - host: nginx.LABSERVERNAME
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: lab-nginx-service
              port:
                number: 80