version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_USER=wordpress
      - MARIADB_ROOT_PASSWORD=yourpassword
      - MARIADB_DATABASE=wordpress
    networks:
      - database_net

  wordpress:
    image: docker.io/bitnami/wordpress:5
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=yourpassword
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_BLOG_NAME=AB_Training_Docker_Compose
    networks:
      - external_net
      - database_net

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  external_net:
    driver: bridge
  database_net:
    driver: bridge